# LOADING DATA INTO NUMPY ARRAY
---

In [1]:
import numpy as np

In [ ]:
# Load data from a text file, with missing values handled as specified.
data = np.genfromtxt('file.txt',delimiter=',')
data = data.astype('int32') # float by default

Now `data` can be used as any numpy array.

In [ ]:
# Creating boolean masks
data > 50

In [ ]:
data [[data <0, axis=0]]

# ADVANCED INDEXING IN NUMPY ARRAYS
---

In [7]:
A = np.array([
              [1,10,1,99,99],
              [6,7,11,9,1],
              [1,2,3,12,5],
              [1,2,3,4,13],
              [4,2,5,99,99],
              [5,3,2,99,99]
])
A

array([[ 1, 10,  1, 99, 99],
       [ 6,  7, 11,  9,  1],
       [ 1,  2,  3, 12,  5],
       [ 1,  2,  3,  4, 13],
       [ 4,  2,  5, 99, 99],
       [ 5,  3,  2, 99, 99]])

In [6]:
# Output [10,11,12,13]
A[[0,1,2,3],[1,2,3,4]]

array([10, 11, 12, 13])

In [9]:
# Output [99,99,99,99,99,99]
A[[0,4,5],3:]

array([[99, 99],
       [99, 99],
       [99, 99]])