<font color='BLUE'>MY NOTES FROM [**'DATA ANALYSIS WITH PYTHON'**](https://www.freecodecamp.org/learn/data-analysis-with-python/data-analysis-with-python-course) COURSE ON FREECODECAMP</font>

# **NUMPY INTRODUCTION**
***
* It's a numeric processing library used for scientific computing with python
* Often it isn't worked with directly
* Libraries like pandas and matplotlib that are frequently used are built on top of Numpy

In [94]:
import numpy as np

# **WHY DO YOU NEED NUMPY?**
***
* EFFICIENT MEMORY HANDLING
* FASTER COMPUTATION AND BETTER PERFORMANCE
* LEAST WASTAGE OF MEMORY


# **Creating arrays using Numpy**
***


## **1-D ARRAYS**

In [95]:
# Creating 1-D array
a = np.array ([1,2,3])
a

array([1, 2, 3])

In [96]:
# slicing
a[::-1]

array([3, 2, 1])

In [97]:
# Multi indexing
a[0], a[2]

(1, 3)

In [98]:
# Multi indexing -- creates another numpy array
a[[0,2]]

array([1, 3])

In [99]:
# Default is usually int64 data type for integers and float64 for floats
a.dtype 

dtype('int64')

In [100]:
# Explicitly making array for 8-bits/1 Byte to save memory and have faster computation
a = np.array([1,2,3], dtype = np.int8)
a.dtype

dtype('int8')

In [101]:
a = np.array([1,2,3], dtype = np.float)
a

array([1., 2., 3.])

## **2-D ARRAYS**

In [102]:
# Creating 2-D array
b = np.array([
              [1,2,3], 
              [3,2,1]
])
b

array([[1, 2, 3],
       [3, 2, 1]])

In [103]:
# Size of array as (rows,columns)
b.shape

(2, 3)

In [104]:
# Dimensions of array
b.ndim

2

In [105]:
# Size of array/ Number of elements in array
b.size

6

## **3-D ARRAYS**

In [106]:
c = np.array([
              [1,2,3],
              [3,2,1],
              [1,3,2]
])
c

array([[1, 2, 3],
       [3, 2, 1],
       [1, 3, 2]])

In [107]:
# accessing multi dimensional array
c[1]

array([3, 2, 1])

In [108]:
# indexing
c[1][2]

1

In [109]:
# indexing
c[1,2]

1

In [110]:
# Slicing
c[1:3]

array([[3, 2, 1],
       [1, 3, 2]])

In [111]:
# Slicing and indexing
c[:,:2]

array([[1, 2],
       [3, 2],
       [1, 3]])

In [112]:
# Slicing and indexing
c[:2,2:]

array([[3],
       [1]])

In [113]:
# Reassigning rows
c[1] = np.array([10,20,20])
c

array([[ 1,  2,  3],
       [10, 20, 20],
       [ 1,  3,  2]])

In [114]:
# Reassigning columns
c[:,2] = np.array([300,200,200])
c

array([[  1,   2, 300],
       [ 10,  20, 200],
       [  1,   3, 200]])

# **Summary statistics of a Numpy array**
***

In [115]:
d = np.array([1,4,6,2,8,9,23,41])

In [116]:
# Summary of all elements
d.sum(), d.mean(), d.std(), d.var()

(94, 11.75, 12.784267675545596, 163.4375)

In [117]:
e = np.array([
              [1,2,3],
              [3,4,5],
              [5,6,7]
])

In [118]:
# Summary of all elements in an N-D array 
e.sum(), e.mean(), e.std(), e.var()

(36, 4.0, 1.8257418583505538, 3.3333333333333335)

In [119]:
# Summary along a particular axis (0 for horizontal, 1 for vertical, can keep increasing as dimension increases)
e.sum(axis=0), e.sum(axis=1)

(array([ 9, 12, 15]), array([ 6, 12, 18]))

# **Numpy operations**
***

In [120]:
# Creating a sample array
a = np.arange(0,5,2)
a

array([0, 2, 4])

In [121]:
# Adding 10 to all elementa of 'a' but not in actual array itself
a+10

array([10, 12, 14])

In [122]:
# Unchanged array
a

array([0, 2, 4])

In [123]:
# Adding 20 to all elements of 'a' and saving changing in the array
a += 20
a

array([20, 22, 24])

In [124]:
# Array x Array multiplication; must have same shape
b = np.array([0,2,1])
a+b , a-b, a*b, b/a

(array([20, 24, 25]),
 array([20, 20, 23]),
 array([ 0, 44, 24]),
 array([0.        , 0.09090909, 0.04166667]))

In [125]:
# Masking
b[[False,True,False]]

array([2])

In [126]:
# Filtering 
b<2, b[b<2]

(array([ True, False,  True]), array([0, 1]))

In [127]:
# Creating random array
c = np.random.randint(50,100, size = (3,3))
c

array([[75, 85, 64],
       [96, 90, 61],
       [72, 95, 76]])

In [128]:
# Filtering
c[c >75]

array([85, 96, 90, 95, 76])

In [129]:
# Dot product
c.dot(b), b.dot(c)

(array([234, 241, 266]), array([264, 275, 198]))

In [130]:
# Dot product 
b @ c, c @ b

(array([264, 275, 198]), array([234, 241, 266]))

In [131]:
# Transpose of array
c.T

array([[75, 96, 72],
       [85, 90, 95],
       [64, 61, 76]])

In [132]:
# Sum of squares
np.sum(b**2)

5

### Creating random arrays

In [133]:
#Return random floats in [0.0, 1.0)
np.random.random(size=4)

array([0.9112749 , 0.97529231, 0.01875716, 0.97918572])

In [134]:
# Creating an array of the given shape with random samples from a uniform distribution over [0, 1)
np.random.rand(2, 4)

array([[0.96231042, 0.45147075, 0.90787864, 0.4775338 ],
       [0.89783386, 0.91179413, 0.96969119, 0.89025465]])

In [135]:
 # Returns random samples from a normal (Gaussian) distribution
np.random.normal(size=2)

array([-1.61299991,  0.38827792])

### Reshaping arrays

In [136]:
b.reshape(3,1)

array([[0],
       [2],
       [1]])

### Zeros, Ones, empty, eye, identity

* `zeros` : Return a new array setting values to zero
* `ones` : Return a new array setting values to one
* `empty_like` : Return an empty array with shape and type of input
* `full` : Return a new array of given shape filled with value
---
* `empty`, unlike `zeros`, does not set the array values to zero,
and may therefore be marginally faster.  
* it requires the user to manually set all the values in the array

In [137]:
# zeros(shape, dtype=float, order='C')
np.zeros((2,2), int)

array([[0, 0],
       [0, 0]])

In [138]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [139]:
# Similar to zeros
np.ones((3,3),int)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [140]:
np.empty(2)

array([1.61299991, 0.38827792])

In [141]:
# Returns an identity square array with ones on the main diagonal
np.identity(3,int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [142]:
# Returns a 2-D array with ones on the diagonal and zeros elsewhere
np.eye(2,dtype=int)

array([[1, 0],
       [0, 1]])

In [143]:
# Third argument k=0 by default; Positive integer means upper diagonal and negative means lower diagonal
np.eye(3,4,1,int)

array([[0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [144]:
np.eye(3,4,-1,int)

array([[0, 0, 0, 0],
       [1, 0, 0, 0],
       [0, 1, 0, 0]])

In [145]:
np.eye(5, k=3,dtype=int)

array([[0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])